---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@upload-brew-tap-to-artifact
    with:
      go-version-file: go.mod
      aqua_policy_allow: true
      aqua_version: v2.48.1
      app_token_repositories: >-
        [
          "${{github.event.repository.name}}",
        ]
    permissions:
      contents: write
      id-token: write
      actions: read
      attestations: write
